name: cups_flutter
description: "CUPS plugin for Flutter"
version: 3.0.0
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CupsFlutterPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: CupsFlutterPlugin
      macos:
        pluginClass: CupsFlutterPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: CupsFlutterPluginCApi
